---
- name: Install base packages
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: latest
        update_cache: yes
    
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Install pip
      apt:
        name: python3-pip
        state: latest

    - name: Install docker pip
      pip:
       name: docker
