---
- name: Install MariaDB
  become: true
  become_user: root
  hosts: db

  vars:
    db_volume_name: mariadb

  tasks:
    - name: Deploy MariaDB server
      docker_container:
        image: mariadb
        name: mariadb
        volumes:
          - "{{ db_volume_name }}:/var/lib/mysql"
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: very-secure-password
          MYSQL_PASSWORD: some-very-secure-password
          MYSQL_DATABASE: wordpress
          MYSQL_USER: devops
