---
- name: Run base.yml playbook
  import_playbook: base.yml
  tags:
    - base

- name: Install wordpress
  become: true
  become_user: root
  hosts: web

  roles:
    - role: install-wordpress
      tags:
        - wordpress
