---
- name: Deploy WordPress
  docker_container:
    image: wordpress
    name: wordpress
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - "{{ wordpress_volume_name }}:/var/www/html"
    env:
      MYSQL_PASSWORD: some-very-secure-password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: devops
      MYSQL_HOST: 192.168.60.99
